#!/usr/bin/env bash
set -euo pipefail

workspace_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

exec nix develop --quiet --no-write-lock-file "path:$workspace_dir" --command arm-none-eabi-nm "$@"
